{
 "title": "Docker Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Failed health checks",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_health_checks_failed_total"
    }
   ]
  },
  {
   "title": "Containers state",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "engine_daemon_container_states_containers{state=\"paused\"}",
     "legendFormat": "Paused"
    },
    {
     "expr": "engine_daemon_container_states_containers{state=\"stopped\"}",
     "legendFormat": "Stopped"
    }
   ]
  },
  {
   "title": "Actions count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "engine_daemon_network_actions_seconds_count",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Events total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 18 },
   "targets": [
    { "expr": "engine_daemon_events_total", "legendFormat": "Events total" }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes / 1073741824",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}