---
- name: Build Docker images
  hosts: all
  tasks:

    - name: Copy docker-images folder
      ansible.builtin.copy:
        src: ../docker-images/nginx
        dest: /tmp/
        mode: "0755"

    - name: Build Nginx image
      community.docker.docker_image:
        source: build
        name: "nginx-1.25.3-daemontools:1.0.0"
        build:
          nocache: true
          path: /tmp/nginx
