---
- name: Setup Grafana
  hosts: all
  remote_user: root
  become: true
  gather_facts: false
  tasks:

    # - name: Create a Grafana container
    #   community.docker.docker_container:
    #     name: grafana
    #     image: pavmark/grafana-debian:release-10.0.10
    #     state: started
    #     recreate: true
    #     pull: true
    #     log_driver: journald
    #     restart_policy: always
    #     ports:
    #       - "3000:3000"
    #     networks:
    #       - name: monitoring

    - name: Add data source
      grafana.grafana.datasource:
        dataSource: |
          {
            "name": "Prometheushhh",
            "type": "prometheus",
            "access": "proxy",
            "url": "http://prometheus:9090",
            "jsonData": {
              "httpMethod": "POST",
              "manageAlerts": true,
              "prometheusType": "Prometheus",
              "cacheLevel": "High"
            }
          }
        grafana_url: "http://127.0.0.1:3000"
        grafana_api_key: "glsa_sc75rIwt33nNJqfIPdRXRP61LpQEVs5f_90cebb5b"

    - name: Add docker dashboard
      grafana.grafana.dashboard:
        # dashboard: "../configs/grafana/dashboards/dockerMetrics.json"
        dashboard: "{{ lookup('ansible.builtin.file', '../configs/grafana/dashboards/dockerMetrics.json') }}"
        grafana_url: "http://127.0.0.1:3000"
        grafana_api_key: "glsa_sc75rIwt33nNJqfIPdRXRP61LpQEVs5f_90cebb5b"
        state: present
