---
- name: Setup Grafana
  hosts: all
  vars_files:
    - ../vars/grafana/admin.yaml
  tasks:

    - name: Copy nginx proxy config
      ansible.builtin.copy:
        src: ../configs/grafana/
        dest: /etc/docker/grafana
        mode: "0644"

    - name: Create a Grafana container
      community.docker.docker_container:
        name: grafana
        image: pavmark/grafana-debian:release-10.0.10
        state: started
        recreate: true
        pull: true
        log_driver: journald
        restart_policy: always
        env:
          GF_SECURITY_ADMIN_USER: "{{ GRAFANA_ADMIN_USER }}"
          GF_SECURITY_ADMIN_PASSWORD: "{{ GRAFANA_ADMIN_PASSWORD }}"
        ports:
          - "3000:3000"
        networks:
          - name: monitoring
        mounts:
          - type: bind
            target: /etc/grafana/provisioning/
            source: /etc/docker/grafana/
            read_only: true
