---
- name: Setup host
  hosts: all
  remote_user: root
  become: true
  tasks:

    - name: Save current state of the firewall in system file
      ansible.builtin.debug:
        msg: dawdawd"{{ item }}"
      loop: "{{ range(1, 6) }}"
